### ISSUE TITLE
Built-in updates check isnt working

### ISSUE THREAD

**Issue by evgkrsk** [objective-see/OverSight#11]
I noticed that "Check now" button didnt find out any new versions. Now, version check in 1.2.0 didnt discover 2.0:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/79869/117907641-55c14200-b301-11eb-858e-974f947f9a1c.png">

Is this expected behavior?

**Comment by objective-see** [comment]
Yes ...for now. Before triggering the auto-update alert to *everybody* ...want to make sure it has no major issues 😅

**Comment by evgkrsk** [comment]
Sound legit, but my point is that this function wasn't working even with 1.x.x. releases too. Never, as long as I use Oversight.

**Comment by k0pernicus** [comment]
@evgkrsk Does this means that you could not trigger the 1.2.0 with the older version?

Based on the 1.2.0 information (from the build itself, downloaded from the website), the 1.2.0 version app has been created in September 2017 - so I don't think there was any new version of it since... 3 years now, except the new 2.0.0.

**Comment by evgkrsk** [comment]
Oooops, seems like I mix up oversight with some another program. You are right, 1.2.0 is 3+ years old and I use it less that one year. Thanks for pointing out.

Sorry for inconvience, closing.
