### ISSUE TITLE
Broken for MacOS

### ISSUE THREAD

**Issue by PrlvacyGuru** [objective-see/OverSight#27]
Even after giving proper permissions/access, my microphone & camera can be activated and OverSight will not notify me or attempt to block it. It does not detect that they have been activated. Machine: MacOS Monterey v.12.4.

**Comment by hzz888** [comment]
Macos 12.6 the same issue. Not work at all.

**Comment by objective-see** [comment]
The latest version (v2.1.1) has been updated to work with recent versions of macOS. 

You can grab it from: https://github.com/objective-see/OverSight/releases/download/v2.1.1/OverSight_2.1.1.zip

**Comment by objective-see** [comment]
Ah, thanks for this info. 
Spent some time digging turns out that now macOS defaults that notification style to "Banners" which are automatically dismissed by the OS 😭

Worse there is now no way programmatically to toggle this mode to "Alerts"

> Apple believes it may be harmful if applications decide on the default alert style even though users can override the setting in the System Preferences anyway. I was recommended to create a notification system of my own if I needed such behaviour. 

 (See: https://stackoverflow.com/questions/69782010/is-it-possible-to-set-default-alert-style-for-macos-unnotification#comment127842826_69782010). 

So you have to manually go into the Notifications pane in System Preferences and toggle the style to "Alerts":
<img width="715" alt="darkMode" src="https://user-images.githubusercontent.com/11327812/203672281-22019a1b-6a89-44f7-918b-307974c8580b.png">

I've just updated the installer / app (commit: 9f00793fa3175b15e362adc6a26ca4a5e99ddaff ) to explain this more to the user, and assist w/ turning on this notification mode. Will release a new version with these updates shortly!
