### ISSUE TITLE
2.1.4 Install fails if not admin

### ISSUE THREAD

**Issue by rothaar** [objective-see/OverSight#38]
Seems to fail somewhat ungracefully if you try to install from a regular user account, rather than asking to authenticate, even when one tries to use the sudo CLI approach. Is it truly intended only to install when logged into the GUI as an admin? Below is the error I receive when running, from an admin/sudoers account:

sudo Downloads/OverSight\ Installer.app/Contents/MacOS/OverSight\ Installer -install

<img width="267" alt="Screen Shot 2022-12-13 at 21 37 59" src="https://user-images.githubusercontent.com/164607/207491620-d2bcb3a0-accf-4855-a83e-1d35131ad6c7.png">

**Comment by objective-see** [comment]
"Is it truly intended only to install when logged into the GUI as an admin?" ...unfortunately yes. 

This is because the mechanism the OverSight uses to (continually) monitor for mic/webcam events requires administrative privileges ...so even if you elevate at the time of install, this does suffice. 

A (possible) solution would be to create a launch daemon/service that could then run w/ elevated privileges. However, this would greatly complicate everything about OverSight (as now it's a nice standalone, self-contained app) ...hence the current approach is "only run on default / admin accounts" 🥲

(For more info, see: https://github.com/objective-see/OverSight/issues/34)

**Comment by hmijail** [comment]
> so even if you elevate at the time of install, this does suffice
Did you mean "does NOT suffice"?

I spent a while trying to fix things on my side before coming to find some official information. So would be great to have this info in the tools' page.

**Comment by objective-see** [comment]
@hmijail - good catch, edited the comment to say, "does *not* suffice" 

Also good suggestion, I've added the following to the OverSight page:
![image](https://user-images.githubusercontent.com/11327812/207736312-33af2d8f-bd81-4c16-a36e-d63c3a16df8c.png)

**Comment by hmijail** [comment]
Given that it's under the "Installing Oversight" header, I'm afraid the "run" part is not clear and I'd still think "no problem, I will install from the admin account"... 
... but that might be me.

**Comment by objective-see** [comment]
Fair, further clarified to point out it can only be **installed for** accounts w/ admin privileges:

```
Due to the mechanism used by OverSight to monitor for mic and webcam access, it can only be installed for accounts with administrative privileges (which is the default for accounts on macOS). ```
